#! /usr/bin/env python3

import orion;
import orion.extras;

with orion.extras.Runner("cat", b"ahmad asy syafiq", listen=True) as runner:
    print(runner.stdout.read());

with orion.extras.Runner("python simpleput.py", b"ahmad asy syafiq\nslamet bejo untung", listen=True) as runner:
    print(runner.stdout.read());

process: orion.extras.Runner = orion.extras.Runner("python simpleput.py", b"ahmad asy syafiq\nslamet bejo untung", listen=True);
output: any = process.start();

print(output.stdout.read());

process.close();
# process.terminate();
# process.kill();
